alias kg="k get"
alias kd="k describe"
alias ka="k apply -f"
alias kdel="k delete"
alias kl="k logs"
alias kf="k logs -f"
alias ke="k exec -it"
alias kcp="k cp"

alias kctx="k config use-context"
alias kcc="k config current-context"
alias kns="k config set-context --current --namespace"

alias kgp="kg pods"
alias kgd="kg deploy"
alias kgds="kg ds"
alias kgs="kg svc"
alias kging="kg ingress"
alias kgcm="kg cm"
alias kgsec="kg secret"
alias kgj="kg -o json"
alias kgy="kg -o yaml"

# openshift-cli specific
alias op="o project"
alias ops="o projects"
alias oroute="o get routes"
alias onew="o new-app"
alias ob="o start-build"
alias ost="o status"
alias ow="o whoami"
alias orsh="o rsh"
