alias k="kubectl"
alias kg="kubectl get"
alias kd="kubectl describe"
alias ka="kubectl apply -f"
alias kdel="kubectl delete"
alias kl="kubectl logs"
alias kf="kubectl logs -f"
alias ke="kubectl exec -it"
alias kcp="kubectl cp"

alias kctx="kubectl config use-context"
alias kcc="kubectl config current-context"
alias kns="kubectl config set-context --current --namespace"

alias kgp="kubectl get pods"
alias kgd="kubectl get deploy"
alias kgds="kubectl get ds"
alias kgs="kubectl get svc"
alias kging="kubectl get ingress"
alias kgcm="kubectl get cm"
alias kgsec="kubectl get secret"
alias kgj="kubectl get -o json"
alias kgy="kubectl get -o yaml"

# openshift-cli specific
alias o="oc"
alias op="oc project"
alias ops="oc projects"
alias oroute="oc get routes"
alias onew="oc new-app"
alias ob="oc start-build"
alias ost="oc status"
alias ow="oc whoami"
alias orsh="oc rsh"
